from __future__ import annotations

import argparse
import json
import os
from dataclasses import dataclass
from pathlib import Path


DEFAULT_PROJECT_NAME = "Smoke Test"


@dataclass(frozen=True)
class InitResult:
    root: Path
    project_root: Path
    run_dir: Path
    watch_file: Path
    harvest_command: str
    health_command: str
    created: list[Path]
    kept: list[Path]


def main() -> int:
    parser = argparse.ArgumentParser(description="Initialize a minimal ResearchKB Agent Memory smoke workspace.")
    parser.add_argument("--root", type=Path, help="ResearchKB root. Defaults to RESEARCHKB_ROOT or .runtime/researchkb.")
    parser.add_argument(
        "--project-root",
        type=Path,
        help="Example project root. Defaults to .runtime/example-project.",
    )
    parser.add_argument("--project-name", default=DEFAULT_PROJECT_NAME, help="Project name used in the smoke run.")
    parser.add_argument("--force", action="store_true", help="Overwrite generated smoke files.")
    args = parser.parse_args()

    result = init_workspace(
        root=resolve_root(args.root),
        project_root=resolve_project_root(args.project_root),
        project_name=args.project_name,
        force=args.force,
    )
    print_report(result)
    return 0


def resolve_root(root: Path | None) -> Path:
    if root is not None:
        return root.expanduser().resolve()
    env_root = os.environ.get("RESEARCHKB_ROOT")
    if env_root:
        return Path(env_root).expanduser().resolve()
    return (Path.cwd() / ".runtime" / "researchkb").resolve()


def resolve_project_root(project_root: Path | None) -> Path:
    if project_root is not None:
        return project_root.expanduser().resolve()
    return (Path.cwd() / ".runtime" / "example-project").resolve()


def init_workspace(root: Path, project_root: Path, project_name: str, force: bool = False) -> InitResult:
    root = root.expanduser().resolve()
    project_root = project_root.expanduser().resolve()
    run_dir = project_root / "runs" / "smoke-test"
    watch_file = root / "config" / "auto_harvest_paths.txt"
    created: list[Path] = []
    kept: list[Path] = []

    for directory in [root / "config", root / "exports", root / "auto_ingest", root / "logs", run_dir]:
        if directory.exists():
            kept.append(directory)
        else:
            directory.mkdir(parents=True, exist_ok=True)
            created.append(directory)

    watch_lines = [
        "# Add only narrow project output folders here.",
        str(root / "exports"),
        str(root / "auto_ingest"),
        str(project_root / "runs"),
    ]
    write_text_if_needed(watch_file, "\n".join(watch_lines) + "\n", force, created, kept)

    metrics = {
        "project": project_name,
        "experiment": "smoke-test",
        "run_id": "run_smoke_001",
        "status": "completed_positive",
        "dataset": "synthetic",
        "model": "example-model",
        "metrics": {
            "accuracy": 0.842,
            "latency_ms": 128.5,
        },
        "decision": "continue",
        "next_action": "Replace this smoke run with one real project output folder.",
        "artifacts": ["summary.json"],
        "notes": "Synthetic smoke-test example generated by init_researchkb_workspace.py.",
    }
    write_json_if_needed(run_dir / "metrics.json", metrics, force, created, kept)

    summary = {
        "run_id": "run_smoke_001",
        "summary": "The synthetic smoke test emitted parseable metrics for first ingestion.",
        "expected_agent_use": [
            "Verify that the run was harvested.",
            "Check that metrics are queryable.",
            "Use this as the first end-to-end ingestion test.",
        ],
    }
    write_json_if_needed(run_dir / "summary.json", summary, force, created, kept)

    return InitResult(
        root=root,
        project_root=project_root,
        run_dir=run_dir,
        watch_file=watch_file,
        harvest_command=build_harvest_command(root, project_name, run_dir),
        health_command=f'python researchkb/rk_health.py --root "{root}"',
        created=created,
        kept=kept,
    )


def write_json_if_needed(path: Path, payload: dict, force: bool, created: list[Path], kept: list[Path]) -> None:
    text = json.dumps(payload, ensure_ascii=False, indent=2) + "\n"
    write_text_if_needed(path, text, force, created, kept)


def write_text_if_needed(path: Path, text: str, force: bool, created: list[Path], kept: list[Path]) -> None:
    if path.exists() and not force:
        kept.append(path)
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    created.append(path)


def build_harvest_command(root: Path, project_name: str, run_dir: Path) -> str:
    harvester = root / "rk-harvest.cmd"
    return f'"{harvester}" --project "{project_name}" "{run_dir}"'


def print_report(result: InitResult) -> None:
    print("ResearchKB Agent Memory smoke workspace initialized.")
    print(f"ResearchKB root: {result.root}")
    print(f"Project root: {result.project_root}")
    print(f"Smoke run: {result.run_dir}")
    print(f"Watch-list: {result.watch_file}")
    print("")
    print("Next commands:")
    print(f'$env:RESEARCHKB_ROOT = "{result.root}"')
    print(result.health_command)
    print(result.harvest_command)
    print("")
    print("If rk-harvest.cmd does not exist yet, install or point to your ResearchKB harvester first.")


if __name__ == "__main__":
    raise SystemExit(main())
